# Use a imagem oficial do MySQL como base
FROM mysql:latest

# Define variáveis de ambiente para inicializar o MySQL
ENV MYSQL_ROOT_PASSWORD=123
ENV MYSQL_DATABASE=mysqlteste
ENV MYSQL_USER=douglas
ENV MYSQL_PASSWORD=123

# Exponha a porta padrão do MySQL
EXPOSE 3306
